builds:
  - binary: docker-monitor-cli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: docker-monitor-cli
    homepage: https://github.com/MichaelTolchinsky/homebrew-docker-monitor-cli
    tap:
      owner: MichaelTolchinsky
      name: homebrew-docker-monitor-cli
    commit_author:
      name: MichaelTolchinsky
      email: mishatolchinski@gmail.com

checksum:
  name_template: "checksums.txt"

before:
  hooks:
    - go mod download
    - go generate ./...
